name: Daily Update
on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for proper git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Run Python script
        run: python scripts/increment.py

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.x"
      - name: Run Go script
        run: |
          cd scripts
          go run increment.go

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Rust script
        run: |
          cd scripts
          cargo run increment.rs

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Run JavaScript script
        run: |
          cd javascript
          npm install
          node scripts/increment.js

      - name: Run TypeScript script
        run: |
          cd scripts
          npm install
          npm start

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code numbers.txt || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add numbers.txt
          git commit -m "chore: daily number increment [skip ci]"
          git push