name: Daily Update

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Python script
        run: python scripts/increment.py

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.x"

      - name: Run Go script
        run: go run scripts/increment.go

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run Rust script
        run: cargo run --manifest-path scripts/increment.rs

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Run JavaScript script
        run: node scripts/increment.js

      - name: Run TypeScript script
        run: |
          npm install -g typescript
          tsc scripts/increment.ts

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add numbers.txt
          git commit -m "Daily update: Incremented numbers"
          git push